package com.balamitra.core.localization

import androidx.compose.runtime.compositionLocalOf
import com.balamitra.core.model.Language
import java.util.Calendar

data class Strings(
    // App & Identity
    val appName: String,
    val tagline: String,
    val productStatement: String,

    // Navigation
    val navToday: String,
    val navChildren: String,
    val navObserve: String,
    val navInsights: String,

    // Status & Offline
    val statusOnline: String,
    val statusOffline: String,
    val modeDemo: String,
    val modeReal: String,

    // Auth & Center
    val loginTitle: String,
    val loginSubtitle: String,
    val workerIdLabel: String,
    val centerCodeLabel: String,
    val pinLabel: String,
    val btnLogin: String,
    val btnDemoLogin: String,
    val workerRole: String,
    val centerStatusOpen: String,
    val dailyAttendance: String,
    val hotCookedMeal: String,
    val mealDistributed: String,
    val locationLabel: String,
    val sampleCredentialsTitle: String,
    val logoutBtn: String,
    val markAttendanceBtn: String,
    val attendanceDialogTitle: String,
    val markAllPresent: String,
    val saveAttendance: String,
    val presentLabel: String,
    val absentLabel: String,
    val mealMenuLabel: String,

    // Today Screen
    val todayTitle: String,
    val todaySubtitle: String,
    val priorityAction: String,
    val homeRaviPriorityAction: String,
    val homeAnanyaCategory: String,
    val homeAnanyaAction: String,
    val homeMeenaCategory: String,
    val homeMeenaAction: String,
    val btnOpenStory: String,

    // Children Directory
    val directoryTitle: String,
    val directorySubtitle: String,
    val ageGenderNative: (Int, String, String) -> String,
    val fatherName: String,
    val motherName: String,
    val enrollmentId: String,

    // Child Story
    val childGrowth: String,
    val childNutrition: String,
    val childDevelopment: String,
    val statusStable: String,
    val statusIncreasing: String,
    val statusDecreasing: String,
    val statusNeedsReview: String,
    val btnWhatChanged: String,
    val btnConnectDots: String,
    val btnWhyThis: String,
    val suggestedActionTitle: String,
    val howToConduct: String,
    val workerDecisionTitle: String,
    val btnDoActivity: String,
    val btnChange: String,
    val btnSkip: String,
    val btnExplainParent: String,
    val timelineTitle: String,
    val timelineSubtitle: String,

    // What Changed Dialog
    val whatChangedTitle: String,
    val whatChangedSubtitle: (String) -> String,
    val growthTrajectory: String,
    val developmentProgression: String,
    val areaWorthObserving: String,
    val suggestedNextStep: String,
    val btnUnderstood: String,

    // Connect The Dots Dialog
    val connectDotsTitle: String,
    val connectDotsSubtitle: String,
    val patternNoticedTitle: String,
    val supportingEvidenceTitle: String,
    val considerTryingTitle: String,

    // Why Evidence Dialog
    val whyEvidenceTitle: String,
    val recordedEvidenceTitle: String,
    val reasoningRationaleTitle: String,

    // Worker Override Dialog
    val overrideTitle: String,
    val overrideSubtitle: String,
    val reasonNotSuitable: String,
    val reasonChildTired: String,
    val reasonAlreadyDid: String,
    val reasonDifferentPreferred: String,
    val reasonOther: String,
    val btnSaveChange: String,
    val btnCancel: String,

    // Re-Observe Dialog
    val reobserveTitle: String,
    val outcomeIndependent: String,
    val outcomeIndependentDesc: String,
    val outcomeNeededHelp: String,
    val outcomeNeededHelpDesc: String,
    val outcomeCouldNotDo: String,
    val outcomeCouldNotDoDesc: String,
    val adaptiveLearnMessage: String,

    // Parent Mode Dialog
    val parentExplainTitle: String,
    val parentExplainSubtitle: (String) -> String,
    val whatToSayParent: String,
    val simpleHomeActivity: String,
    val btnReadAloud: (String) -> String,
    val btnSpeaking: (String) -> String,
    val btnDone: String,

    // Observe Screen
    val observeTitle: String,
    val observeSubtitle: String,
    val busyMode: String,
    val tapToSpeak: String,
    val listening: (String) -> String,
    val sampleVoiceTitle: String,
    val structuredVerificationTitle: String,
    val btnSaveObservation: String,
    val btnCorrectObservation: String,
    val permissionRequired: String,
    val btnGrantPermission: String,

    // Centre Insights Screen
    val centreInsightsTitle: String,
    val centreInsightsSubtitle: String,
    val childrenObserved: String,
    val activitiesDone: String,
    val followupsPending: String,
    val focusAreasTitle: String,
    val resourceInsightTitle: String,
    val materialsTitle: String,
    val materialsSubtitle: String
)

val EnglishStrings = Strings(
    appName = "BALAMITRA",
    tagline = "Understand every child. Know what to do next.",
    productStatement = "BALAMITRA is an on-device longitudinal intelligence layer that remembers what workers observe, connects patterns across time, and helps them make better-informed decisions.",
    navToday = "Today",
    navChildren = "Children",
    navObserve = "Observe",
    navInsights = "Insights",
    statusOnline = "Online",
    statusOffline = "Offline Mode (100% Local)",
    modeDemo = "Demo Mode",
    modeReal = "Real Anganwadi",
    loginTitle = "Anganwadi Worker Portal",
    loginSubtitle = "Integrated Child Development Services (ICDS)",
    workerIdLabel = "Worker ID (AWW)",
    centerCodeLabel = "Anganwadi Centre Code (AWC)",
    pinLabel = "4-Digit Worker PIN",
    btnLogin = "Sign In to Centre",
    btnDemoLogin = "⚡ Quick Demo Login (Smt. Lakshmi Devi)",
    workerRole = "Anganwadi Worker (AWW)",
    centerStatusOpen = "Centre Open Today",
    dailyAttendance = "Morning Attendance: 18 / 22 Children",
    hotCookedMeal = "Hot Cooked Meal: Distributed (Rice, Dal, Egg)",
    mealDistributed = "Meal Distributed ✓",
    locationLabel = "Bachupally, Medchal-Malkajgiri (Hyderabad), Telangana",
    sampleCredentialsTitle = "Sample Teacher Credentials (Bachupally AWC 1)",
    logoutBtn = "Logout",
    markAttendanceBtn = "Mark Attendance",
    attendanceDialogTitle = "Daily Attendance Register",
    markAllPresent = "Mark All Present",
    saveAttendance = "Save Attendance",
    presentLabel = "Present",
    absentLabel = "Absent",
    mealMenuLabel = "Menu",
    todayTitle = "WHAT SHOULD I DO TODAY?",
    todaySubtitle = "Daily action priorities based on longitudinal observations and center materials",
    priorityAction = "RECOMMENDED ACTION:",
    homeRaviPriorityAction = "Colour Cup Challenge: 5-min 2-step activity using physical cups and caps. Reinforces sequential listening without pressure.",
    homeAnanyaCategory = "Nutrition Follow-up",
    homeAnanyaAction = "Follow up morning snack appetite and note food interest.",
    homeMeenaCategory = "Motor Balance Activity",
    homeMeenaAction = "Outdoor stepping stones balance play with leaves and pebbles.",
    btnOpenStory = "Open Journey",
    directoryTitle = "CHILDREN DIRECTORY",
    directorySubtitle = "Registered children under Bachupally Anganwadi Centre",
    ageGenderNative = { age, gender, native -> "$age yrs • $gender • $native" },
    fatherName = "Father",
    motherName = "Mother",
    enrollmentId = "Enrollment ID",
    childGrowth = "GROWTH",
    childNutrition = "NUTRITION",
    childDevelopment = "DEVELOPMENT",
    statusStable = "Stable",
    statusIncreasing = "Increasing",
    statusDecreasing = "Decreasing",
    statusNeedsReview = "Needs review",
    btnWhatChanged = "WHAT CHANGED?",
    btnConnectDots = "CONNECT DOTS",
    btnWhyThis = "WHY THIS?",
    suggestedActionTitle = "SUGGESTED NEXT ACTION",
    howToConduct = "How to conduct (using center materials):",
    workerDecisionTitle = "WORKER DECISION (You are in control):",
    btnDoActivity = "Do Activity",
    btnChange = "Change",
    btnSkip = "Skip",
    btnExplainParent = "EXPLAIN TO PARENT (Friendly Note)",
    timelineTitle = "LONGITUDINAL TIMELINE",
    timelineSubtitle = "Recorded observations and responses over time",
    whatChangedTitle = "WHAT CHANGED?",
    whatChangedSubtitle = { name -> "Progress for $name since last observation" },
    growthTrajectory = "Growth Trajectory",
    developmentProgression = "Development Progression",
    areaWorthObserving = "Area Worth Observing",
    suggestedNextStep = "Suggested Next Step",
    btnUnderstood = "OK, Understood",
    connectDotsTitle = "CONNECT THE DOTS",
    connectDotsSubtitle = "Longitudinal Pattern Recognition Across Sessions",
    patternNoticedTitle = "I NOTICED A PATTERN",
    supportingEvidenceTitle = "Supporting Historical Evidence",
    considerTryingTitle = "CONSIDER TRYING",
    whyEvidenceTitle = "WHY THIS ACTIVITY?",
    recordedEvidenceTitle = "Recorded Evidence Points",
    reasoningRationaleTitle = "Reasoning Rationale",
    overrideTitle = "Change Activity Suggestion",
    overrideSubtitle = "Your expertise guides the system. Why change this activity?",
    reasonNotSuitable = "Not suitable today",
    reasonChildTired = "Child is tired",
    reasonAlreadyDid = "Child already did this",
    reasonDifferentPreferred = "Different activity preferred",
    reasonOther = "Other reason",
    btnSaveChange = "Save Change",
    btnCancel = "Cancel",
    reobserveTitle = "HOW DID IT GO?",
    outcomeIndependent = "Did Independently",
    outcomeIndependentDesc = "Understood and completed without prompting",
    outcomeNeededHelp = "Needed Help",
    outcomeNeededHelpDesc = "Understood with adult demonstration or clues",
    outcomeCouldNotDo = "Could Not Do",
    outcomeCouldNotDoDesc = "Found it challenging or stopped early",
    adaptiveLearnMessage = "💡 BALAMITRA learned: Recorded this outcome to adapt future activities for this child.",
    parentExplainTitle = "EXPLAIN TO PARENT",
    parentExplainSubtitle = { name -> "Warm, supportive, non-technical explanation for $name's family" },
    whatToSayParent = "WHAT TO TELL THE PARENT:",
    simpleHomeActivity = "SIMPLE 5-MINUTE HOME ACTIVITY:",
    btnReadAloud = { lang -> "Read Aloud in $lang" },
    btnSpeaking = { lang -> "Speaking in $lang…" },
    btnDone = "Done",
    observeTitle = "TELL BALAMITRA",
    observeSubtitle = "Speak naturally in your language or tap a sample",
    busyMode = "Busy Mode",
    tapToSpeak = "Tap microphone and speak",
    listening = { lang -> "Listening in $lang… Speak now" },
    sampleVoiceTitle = "SAMPLE OBSERVATION (TAP TO SIMULATE VOICE):",
    structuredVerificationTitle = "I UNDERSTOOD (STRUCTURED VERIFICATION):",
    btnSaveObservation = "✓ SAVE",
    btnCorrectObservation = "✎ CORRECT",
    permissionRequired = "Microphone permission is required to record speech.",
    btnGrantPermission = "Grant Permission",
    centreInsightsTitle = "CENTRE INSIGHTS",
    centreInsightsSubtitle = "Aggregated, privacy-conscious summary for this Anganwadi centre",
    childrenObserved = "Children Observed",
    activitiesDone = "Activities Done",
    followupsPending = "Follow-ups Pending",
    focusAreasTitle = "Most-Used Activity Focus Areas",
    resourceInsightTitle = "Center Resource Insight",
    materialsTitle = "AVAILABLE MATERIALS (HOME REALITY)",
    materialsSubtitle = "Uncheck items not currently available; suggestions adapt immediately"
)

val TeluguStrings = Strings(
    appName = "బాలమిత్ర",
    tagline = "ప్రతి బిడ్డను అర్థం చేసుకోండి. తర్వాత ఏమి చేయాలో తెలుసుకోండి.",
    productStatement = "బాలమిత్ర అనేది ఆన్-డివైస్ వ్యవస్థ, ఇది అంగన్‌వాడీ కార్యకర్తల పరిశీలనలను గుర్తుంచుకుంటుంది, కాలక్రమేణా మార్పులను గుర్తిస్తుంది మరియు సరైన నిర్ణయాలు తీసుకోవడంలో సహాయపడుతుంది.",
    navToday = "ఈరోజు",
    navChildren = "పిల్లలు",
    navObserve = "పరిశీలన",
    navInsights = "వివరాలు",
    statusOnline = "ఆన్‌లైన్",
    statusOffline = "ఆఫ్‌లైన్ మోడ్ (100% పరికరంలోనే)",
    modeDemo = "డెమో మోడ్",
    modeReal = "రియల్ అంగన్‌వాడీ",
    loginTitle = "అంగన్‌వాడీ కార్యకర్త పోర్టల్",
    loginSubtitle = "సమగ్ర శిశు అభివృద్ధి సేవలు (ICDS)",
    workerIdLabel = "కార్యకర్త ఐడి (AWW)",
    centerCodeLabel = "అంగన్‌వాడీ కేంద్రం కోడ్ (AWC)",
    pinLabel = "4-అంకెల పిన్ (PIN)",
    btnLogin = "కేంద్రంలోకి ప్రవేశించండి",
    btnDemoLogin = "⚡ త్వరిత డెమో లాగిన్ (శ్రీమతి లక్ష్మీ దేవి)",
    workerRole = "అంగన్‌వాడీ కార్యకర్త (AWW)",
    centerStatusOpen = "కేంద్రం తెరిచి ఉంది",
    dailyAttendance = "ఉదయం హాజరు: 18 / 22 పిల్లలు",
    hotCookedMeal = "వేడి భోజనం: పంపిణీ చేయబడింది (అన్నం, పప్పు, గుడ్డు)",
    mealDistributed = "భోజనం పంపిణీ పూర్తయింది ✓",
    locationLabel = "బాచుపల్లి, మేడ్చల్-మల్కాజిగిరి (హైదరాబాద్), తెలంగాణ",
    sampleCredentialsTitle = "నమూనా ఉపాధ్యాయురాలి లాగిన్ వివరాలు (బాచుపల్లి AWC 1)",
    logoutBtn = "లాగౌట్",
    markAttendanceBtn = "హాజరు నమోదు",
    attendanceDialogTitle = "రోజువారీ హాజరు పట్టిక",
    markAllPresent = "అందరినీ హాజరుగా గుర్తించు",
    saveAttendance = "హాజరు భద్రపరచు",
    presentLabel = "హాజరు",
    absentLabel = "గైర్హాజరు",
    mealMenuLabel = "మెనూ",
    todayTitle = "ఈరోజు నేను ఏమి చేయాలి?",
    todaySubtitle = "గత పరిశీలనలు మరియు కేంద్రంలోని వస్తువుల ఆధారంగా నేటి ముఖ్యమైన పనులు",
    priorityAction = "సూచించిన కార్యాచరణ:",
    homeRaviPriorityAction = "రంగుల కప్పుల ఆట: భౌతిక కప్పులు, మూతలతో 5 నిమిషాల 2-దశల సరదా ఆట. ఒత్తిడి లేకుండా వరుస సూచనలను గుర్తుంచుకునేలా చేస్తుంది.",
    homeAnanyaCategory = "పోషణ ఫాలో-అప్",
    homeAnanyaAction = "ఉదయపు అల్పాహారంలో ఆకలి, ఆహారంపై ఆసక్తిని పరిశీలించి నమోదు చేయండి.",
    homeMeenaCategory = "మోటార్ బ్యాలెన్స్ ఆట",
    homeMeenaAction = "ఆకులు, గులకరాళ్లతో అవుట్‌డోర్ బ్యాలెన్స్ అడుగుల ఆట.",
    btnOpenStory = "ప్రయాణం చూడండి",
    directoryTitle = "పిల్లల జాబితా",
    directorySubtitle = "బాచుపల్లి అంగన్‌వాడీ కేంద్రంలో నమోదైన పిల్లలు",
    ageGenderNative = { age, gender, native -> "$age సం. • $gender • $native" },
    fatherName = "తండ్రి",
    motherName = "తల్లి",
    enrollmentId = "నమోదు సంఖ్య",
    childGrowth = "పెరుగుదల",
    childNutrition = "పోషణ",
    childDevelopment = "వికాసం",
    statusStable = "స్థిరంగా ఉంది",
    statusIncreasing = "పెరుగుతోంది",
    statusDecreasing = "తగ్గుతోంది",
    statusNeedsReview = "గమనించాలి",
    btnWhatChanged = "ఏమి మారింది?",
    btnConnectDots = "వివరాలు జోడించండి",
    btnWhyThis = "ఇదే ఎందుకు?",
    suggestedActionTitle = "సూచించిన తదుపరి కార్యాచరణ",
    howToConduct = "చేయించాల్సిన విధానం (వస్తువులను ఉపయోగించి):",
    workerDecisionTitle = "కార్యకర్త నిర్ణయం (మీ నిర్ణయమే ముఖ్యం):",
    btnDoActivity = "కార్యకలాపం చేయించండి",
    btnChange = "మార్చండి",
    btnSkip = "వదిలివేయండి",
    btnExplainParent = "తల్లిదండ్రులకు వివరించండి (సులభ సందేశం)",
    timelineTitle = "కాలక్రమ సమయరేఖ",
    timelineSubtitle = "నమోదైన పరిశీలనలు మరియు ప్రతిస్పందనల చరిత్ర",
    whatChangedTitle = "ఏమి మారింది?",
    whatChangedSubtitle = { name -> "గత పరిశీలన నుండి $name ప్రగతిలో మార్పులు" },
    growthTrajectory = "పెరుగుదల సరళి",
    developmentProgression = "వికాస పురోగతి",
    areaWorthObserving = "గమనించాల్సిన విభాగం",
    suggestedNextStep = "సూచించిన తదుపరి చర్య",
    btnUnderstood = "సరే, అర్థమైంది",
    connectDotsTitle = "వివరాలను అనుసంధానించండి",
    connectDotsSubtitle = "గత పరిశీలనల మధ్య గుర్తించిన సరళి",
    patternNoticedTitle = "గమనించిన అనుసంధానం",
    supportingEvidenceTitle = "చరిత్ర నుండి సహాయక ఆధారాలు",
    considerTryingTitle = "ప్రయత్నించదగిన ఆలోచన",
    whyEvidenceTitle = "ఈ కార్యాచరణనే ఎందుకు సూచించాం?",
    recordedEvidenceTitle = "నమోదైన ఆధారాలు",
    reasoningRationaleTitle = "తార్కిక కారణం",
    overrideTitle = "కార్యాచరణ సూచనను మార్చండి",
    overrideSubtitle = "మీ అనుభవమే వ్యవస్థకు మార్గదర్శకం. ఎందుకు మార్చాలనుకుంటున్నారు?",
    reasonNotSuitable = "ఈరోజు సరిపోదు",
    reasonChildTired = "పిల్లాడు అలసిపోయాడు",
    reasonAlreadyDid = "ఇది ఇప్పటికే చేశాడు",
    reasonDifferentPreferred = "వేరే కార్యాచరణ కావాలి",
    reasonOther = "ఇతర కారణం",
    btnSaveChange = "మార్పును సేవ్ చేయండి",
    btnCancel = "రద్దు చేయండి",
    reobserveTitle = "కార్యకలాపం ఎలా జరిగింది?",
    outcomeIndependent = "స్వయంగా చేయగలిగారు",
    outcomeIndependentDesc = "ఎవరి సహాయం లేకుండా పూర్తి చేశారు",
    outcomeNeededHelp = "సహాయం అవసరమైంది",
    outcomeNeededHelpDesc = "చూపించిన తర్వాత మాత్రమే చేయగలిగారు",
    outcomeCouldNotDo = "చేయలేకపోయారు",
    outcomeCouldNotDoDesc = "కష్టంగా అనిపించింది లేదా మధ్యలోనే ఆగారు",
    adaptiveLearnMessage = "💡 బాలమిత్ర నేర్చుకుంది: ఈ ప్రతిస్పందన ఆధారంగా భవిష్యత్ కార్యాచరణలు మారుతాయి.",
    parentExplainTitle = "తల్లిదండ్రులకు వివరణ",
    parentExplainSubtitle = { name -> "$name కుటుంబ సభ్యుల కోసం సులభమైన, సానుకూల సందేశం" },
    whatToSayParent = "తల్లిదండ్రులకు చెప్పాల్సిన మాటలు:",
    simpleHomeActivity = "ఇంట్లో ఆడుకోగల 5 నిమిషాల సరళమైన ఆట:",
    btnReadAloud = { lang -> "$lang లో వినండి" },
    btnSpeaking = { lang -> "$lang లో వినిపిస్తోంది…" },
    btnDone = "పూర్తయింది",
    observeTitle = "బాలమిత్రకు చెప్పండి",
    observeSubtitle = "మీ భాషలో సహజంగా మాట్లాడండి లేదా నమూనా నొక్కండి",
    busyMode = "శీఘ్ర మోడ్",
    tapToSpeak = "మైక్ నొక్కి మాట్లాడండి",
    listening = { lang -> "$lang లో వింటోంది… ఇప్పుడు మాట్లాడండి" },
    sampleVoiceTitle = "నమూనా పరిశీలన (వాయిస్ అనుకరించడానికి నొక్కండి):",
    structuredVerificationTitle = "నేను అర్థం చేసుకున్నది (ధృవీకరణ):",
    btnSaveObservation = "✓ సేవ్ చేయండి",
    btnCorrectObservation = "✎ సవరించండి",
    permissionRequired = "వాయిస్ రికార్డ్ చేయడానికి మైక్రోఫోన్ అనుమతి అవసరం.",
    btnGrantPermission = "అనుమతించండి",
    centreInsightsTitle = "కేంద్రం వివరాలు",
    centreInsightsSubtitle = "ఈ అంగన్‌వాడీ కేంద్రం యొక్క సమగ్ర సారాంశం",
    childrenObserved = "పరిశీలించిన పిల్లలు",
    activitiesDone = "పూర్తయిన కార్యాచరణలు",
    followupsPending = "బాకీ ఉన్న పనులు",
    focusAreasTitle = "ఎక్కువగా ఉపయోగించిన వికాస రంగాలు",
    resourceInsightTitle = "కేంద్ర వనరుల అంతర్దృష్టి",
    materialsTitle = "అందుబాటులో ఉన్న వస్తువులు (కేంద్రం & ఇల్లు)",
    materialsSubtitle = "ప్రస్తుతం లేని వస్తువులను అన్‌చెక్ చేయండి; సూచనలు స్వయంచాలకంగా సర్దుబాటు అవుతాయి"
)

val HindiStrings = Strings(
    appName = "बालमित्र",
    tagline = "हर बच्चे को समझें। आगे क्या करना है जानें।",
    productStatement = "बालमित्र एक ऑन-डिवाइस समझ प्रणाली है जो कार्यकर्ताओं के दैनिक अवलोकनों को याद रखती है, समय के साथ पैटर्न जोड़ती है और बेहतर निर्णय लेने में मदद करती है।",
    navToday = "आज का कार्य",
    navChildren = "बच्चे",
    navObserve = "अवलोकन",
    navInsights = "अंतर्दृष्टि",
    statusOnline = "ऑनलाइन",
    statusOffline = "ऑफ़लाइन मोड (100% स्थानीय)",
    modeDemo = "डेमो मोड",
    modeReal = "वास्तविक केंद्र",
    loginTitle = "आंगनवाड़ी कार्यकर्ता पोर्टल",
    loginSubtitle = "एकीकृत बाल विकास सेवाएं (ICDS)",
    workerIdLabel = "कार्यकर्ता आईडी (AWW)",
    centerCodeLabel = "आंगनवाड़ी केंद्र कोड (AWC)",
    pinLabel = "4-अंकीय पिन (PIN)",
    btnLogin = "केंद्र में प्रवेश करें",
    btnDemoLogin = "⚡ त्वरित डेमो लॉगिन (श्रीमती लक्ष्मी देवी)",
    workerRole = "आंगनवाड़ी कार्यकर्ता (AWW)",
    centerStatusOpen = "केंद्र आज खुला है",
    dailyAttendance = "सुबह की उपस्थिति: 18 / 22 बच्चे",
    hotCookedMeal = "गर्म पका भोजन: वितरित (चावल, दाल, अंडा)",
    mealDistributed = "भोजन वितरित किया गया ✓",
    locationLabel = "बाचुपल्ली, मेडचल-मलकाजगिरी (हैदराबाद), तेलंगाना",
    sampleCredentialsTitle = "नमूना शिक्षक क्रेडेंशियल्स (बाचुपल्ली AWC 1)",
    logoutBtn = "लॉगआउट",
    markAttendanceBtn = "उपस्थिति दर्ज करें",
    attendanceDialogTitle = "दैनिक उपस्थिति रजिस्टर",
    markAllPresent = "सभी को उपस्थित चिह्नित करें",
    saveAttendance = "उपस्थिति सहेजें",
    presentLabel = "उपस्थित",
    absentLabel = "अनुपस्थित",
    mealMenuLabel = "मेनू",
    todayTitle = "आज मुझे क्या करना चाहिए?",
    todaySubtitle = "पिछले अवलोकनों और केंद्र सामग्री के आधार पर प्राथमिकताएं",
    priorityAction = "सुझाई गई गतिविधि:",
    homeRaviPriorityAction = "रंग-बिरंगे कप गतिविधि: कप और ढक्कन से 5 मिनट का 2-चरणीय खेल। बिना दबाव के लगातार निर्देशों को याद रखने में मदद करती है।",
    homeAnanyaCategory = "पोषण फॉलो-अप",
    homeAnanyaAction = "सुबह के नाश्ते में भूख और भोजन में रुचि पर ध्यान दें।",
    homeMeenaCategory = "शारीरिक संतुलन गतिविधि",
    homeMeenaAction = "पत्तों और कंकड़ों के साथ बाहर संतुलन बनाकर चलने वाला खेल।",
    btnOpenStory = "विकास यात्रा देखें",
    directoryTitle = "बच्चों की सूची",
    directorySubtitle = "बाचुपल्ली आंगनवाड़ी केंद्र में पंजीकृत बच्चे",
    ageGenderNative = { age, gender, native -> "$age वर्ष • $gender • $native" },
    fatherName = "पिता",
    motherName = "माता",
    enrollmentId = "पंजीकरण संख्या",
    childGrowth = "शारीरिक वृद्धि",
    childNutrition = "पोषण",
    childDevelopment = "समग्र विकास",
    statusStable = "स्थिर",
    statusIncreasing = "बढ़ रहा है",
    statusDecreasing = "घट रहा है",
    statusNeedsReview = "समीक्षा आवश्यक",
    btnWhatChanged = "क्या बदला?",
    btnConnectDots = "कड़ियों को जोड़ें",
    btnWhyThis = "यही क्यों?",
    suggestedActionTitle = "सुझाया गया अगला कदम",
    howToConduct = "कराने का तरीका (उपलब्ध सामग्री से):",
    workerDecisionTitle = "कार्यकर्ता का निर्णय (आपका निर्णय सर्वोपरि है):",
    btnDoActivity = "गतिविधि कराएं",
    btnChange = "बदलें",
    btnSkip = "छोड़ें",
    btnExplainParent = "अभिभावक को समझाएं (सरल संदेश)",
    timelineTitle = "समयरेखा",
    timelineSubtitle = "दर्ज अवलोकनों और प्रतिक्रियाओं का इतिहास",
    whatChangedTitle = "क्या बदला?",
    whatChangedSubtitle = { name -> "पिछले अवलोकन के बाद से $name की प्रगति" },
    growthTrajectory = "वृद्धि की स्थिति",
    developmentProgression = "विकास प्रगति",
    areaWorthObserving = "ध्यान देने योग्य क्षेत्र",
    suggestedNextStep = "सुझाया गया अगला कदम",
    btnUnderstood = "ठीक है, समझ गए",
    connectDotsTitle = "कड़ियों को जोड़ें",
    connectDotsSubtitle = "सत्रों के बीच देखा गया संबंध",
    patternNoticedTitle = "देखा गया पैटर्न",
    supportingEvidenceTitle = "इतिहास से सहायक साक्ष्य",
    considerTryingTitle = "सुझाया गया विचार",
    whyEvidenceTitle = "इस गतिविधि का सुझाव क्यों दिया गया?",
    recordedEvidenceTitle = "दर्ज प्रमाण",
    reasoningRationaleTitle = "तार्किक कारण",
    overrideTitle = "गतिविधि का सुझाव बदलें",
    overrideSubtitle = "आपका अनुभव इस प्रणाली का मार्गदर्शन करता है। आप इसे क्यों बदलना चाहते हैं?",
    reasonNotSuitable = "आज के लिए उपयुक्त नहीं",
    reasonChildTired = "बच्चा थका हुआ है",
    reasonAlreadyDid = "बच्चा यह पहले कर चुका है",
    reasonDifferentPreferred = "दूसरी गतिविधि पसंद है",
    reasonOther = "अन्य कारण",
    btnSaveChange = "परिवर्तन सहेजें",
    btnCancel = "रद्द करें",
    reobserveTitle = "गतिविधि कैसी रही?",
    outcomeIndependent = "स्वयं किया",
    outcomeIndependentDesc = "बिना किसी संकेत के पूरा किया",
    outcomeNeededHelp = "मदद की ज़रूरत पड़ी",
    outcomeNeededHelpDesc = "मार्गदर्शन के बाद ही कर सके",
    outcomeCouldNotDo = "नहीं कर सका",
    outcomeCouldNotDoDesc = "कठिन लगा या बीच में छोड़ दिया",
    adaptiveLearnMessage = "💡 बालमित्र ने सीखा: भविष्य की गतिविधियों के लिए यह परिणाम दर्ज कर लिया गया।",
    parentExplainTitle = "अभिभावक को समझाएं",
    parentExplainSubtitle = { name -> "$name के परिवार के लिए सरल और आत्मीय संदेश" },
    whatToSayParent = "अभिभावक से क्या कहें:",
    simpleHomeActivity = "घर पर आज़माने के लिए 5 मिनट का सरल खेल:",
    btnReadAloud = { lang -> "$lang में सुनें" },
    btnSpeaking = { lang -> "$lang में बोल रहा है…" },
    btnDone = "पूर्ण",
    observeTitle = "बालमित्र को बताएं",
    observeSubtitle = "अपनी भाषा में बोलें या उदाहरण पर टैप करें",
    busyMode = "त्वरित मोड",
    tapToSpeak = "माइक दबाएं और बोलें",
    listening = { lang -> "$lang में सुन रहा हूँ… बोलिए" },
    sampleVoiceTitle = "उदाहरण अवलोकन (आवाज़ अनुकरण के लिए टैप करें):",
    structuredVerificationTitle = "मैंने समझा (संरचित सत्यापन):",
    btnSaveObservation = "✓ सहेजें",
    btnCorrectObservation = "✎ सुधारें",
    permissionRequired = "आवाज़ रिकॉर्ड करने के लिए माइक्रोफ़ोन अनुमति आवश्यक है।",
    btnGrantPermission = "अनुमति दें",
    centreInsightsTitle = "केंद्र अंतर्दृष्टि",
    centreInsightsSubtitle = "इस आंगनवाड़ी केंद्र का समग्र और सुरक्षित सारांश",
    childrenObserved = "अवलोकन किए गए बच्चे",
    activitiesDone = "पूर्ण गतिविधियाँ",
    followupsPending = "लंबित अनुवर्ती कार्य",
    focusAreasTitle = "सक्रिय विकास क्षेत्र",
    resourceInsightTitle = "केंद्र संसाधन अंतर्दृष्टि",
    materialsTitle = "उपलब्ध सामग्री (केंद्र और घर)",
    materialsSubtitle = "जो सामग्री अभी उपलब्ध नहीं है उसे अनचेक करें; सुझाव तुरंत अनुकूलित होंगे"
)

fun getStrings(language: Language): Strings {
    return when (language) {
        Language.TELUGU -> TeluguStrings
        Language.HINDI -> HindiStrings
        Language.ENGLISH -> EnglishStrings
    }
}

val LocalAppStrings = compositionLocalOf { EnglishStrings }


fun getDayOfWeekLocalized(calendarDay: Int, lang: Language): String {
    return when (calendarDay) {
        Calendar.MONDAY -> when (lang) {
            Language.TELUGU -> "సోమవారం"
            Language.HINDI -> "सोमवार"
            Language.ENGLISH -> "Monday"
        }
        Calendar.TUESDAY -> when (lang) {
            Language.TELUGU -> "మంగళవారం"
            Language.HINDI -> "मंगलवार"
            Language.ENGLISH -> "Tuesday"
        }
        Calendar.WEDNESDAY -> when (lang) {
            Language.TELUGU -> "బుధవారం"
            Language.HINDI -> "बुधवार"
            Language.ENGLISH -> "Wednesday"
        }
        Calendar.THURSDAY -> when (lang) {
            Language.TELUGU -> "గురువారం"
            Language.HINDI -> "गुरुवार"
            Language.ENGLISH -> "Thursday"
        }
        Calendar.FRIDAY -> when (lang) {
            Language.TELUGU -> "శుక్రవారం"
            Language.HINDI -> "शुक्रवार"
            Language.ENGLISH -> "Friday"
        }
        Calendar.SATURDAY -> when (lang) {
            Language.TELUGU -> "శనివారం"
            Language.HINDI -> "शनिवार"
            Language.ENGLISH -> "Saturday"
        }
        else -> when (lang) {
            Language.TELUGU -> "ఆదివారం"
            Language.HINDI -> "रविवार"
            Language.ENGLISH -> "Sunday"
        }
    }
}
